create table "user"
(
    id    bigint generated by default as identity primary key,
    name  varchar(200) not null,
    email varchar(100) not null,
    password varchar(100) not null,
    role    varchar(20),
    constraint chk_user_role
        check (role in ('ROLE_READER', 'ROLE_CREATOR', 'ROLE_ADMIN'))
);

create table course
(
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    description text,
    complexity  varchar(10),
    creator_id   bigint       not null,
    constraint fk_courses_to_user
        foreign key (creator_id)
            references "user" (id)
            on delete cascade,
    constraint chk_course_complexity
        check (complexity in ('EASY', 'MEDIUM', 'HARD'))
);

create table question
(
    id        bigint generated by default as identity primary key,
    question  text   not null,
    answer    text,
    course_id bigint not null,
    constraint fk_questions_to_courses
        foreign key (course_id)
            references course (id)
            on delete cascade
);

create unique index idx_user_email on "user" (email);
create index idx_course_creator_id on course (creator_id);
create index idx_question_course_id on question (course_id);
