create table author
(
    id    bigint generated by default as identity primary key,
    name  varchar(200) not null,
    email varchar(100) not null
);

create table course
(
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    description text,
    complexity  varchar(10),
    author_id   bigint       not null,
    constraint fk_courses_to_author
        foreign key (author_id)
            references author (id)
            on delete cascade,
    constraint chk_course_complexity
        check (complexity in ('EASY', 'MEDIUM', 'HARD'))
);

create table question
(
    id        bigint generated by default as identity primary key,
    question  text   not null,
    answer    text,
    course_id bigint not null,
    constraint fk_lessons_to_courses
        foreign key (course_id)
            references course (id)
            on delete cascade
);

create unique index idx_author_email on author (email);
create index idx_course_author_id on course (author_id);
create index idx_question_course_id on question (course_id);
