create table authors
(
    id    bigint generated by default as identity primary key,
    name  varchar(200) not null,
    email varchar(100) not null
);

create table courses
(
    id        bigint generated by default as identity primary key,
    title     varchar(255) not null,
    author_id bigint       not null,
    constraint fk_courses_to_author
        foreign key (author_id)
            references authors (id)
            on delete cascade
);

create table course_details
(
    id          bigint generated by default as identity primary key,
    description text,
    complexity  varchar(10),
    course_id   bigint not null unique,
    constraint fk_details_to_courses
        foreign key (course_id)
            references courses (id)
            on delete cascade,
    constraint chk_course_complexity
        check (complexity in ('EASY', 'MIDDLE', 'HARD'))
);

create table lessons
(
    id        bigint generated by default as identity primary key,
    title     varchar(255) not null,
    content   text,
    course_id bigint       not null,
    constraint fk_lessons_to_courses
        foreign key (course_id)
            references courses (id)
            on delete cascade
);

